### ISSUE TITLE
problems :(

### ISSUE THREAD

**Issue by gpessia** [hrsetyono/theme_pacific#1]
![schermata 2015-06-12 alle 17 05 38](https://cloud.githubusercontent.com/assets/68612/8132921/5bbd47a0-1125-11e5-8c00-ef72781be679.png)
![schermata 2015-06-12 alle 17 05 50](https://cloud.githubusercontent.com/assets/68612/8132937/6d095b52-1125-11e5-8743-c15040671f58.png)

**Comment by hrsetyono** [comment]
Hi, the error is from [Material theme](https://packagecontrol.io/packages/Material%20Theme) and not this one :)

I just tried installing that theme and get the same error.

**Comment by gpessia** [comment]
:)) yes! ahah
