### ISSUE TITLE
Scrollbar colours?

### ISSUE THREAD

**Issue by lijuenc** [hrsetyono/theme_pacific#2]
First up, excellent theme.

Now, the screenshots in your readme show blue scrollbars which are much more appealing, but I'm getting white ones. This is also the case in the sidebar and command menu scrollbars (ctrl+shift+p, ctrl+p, etc).

![Scrollbar colour](http://i.imgur.com/fseyHvE.png)

Is this intended?

Found out why: you get white scrollbars if you have the `overlay_scroll_bars` enabled in Sublime Text. Still, is this intended?

**Comment by hrsetyono** [comment]
Hi Durz,

Thanks for the report. It is certainly not intended and I will fix it.

I didn't know there is overlay scroll bars setting and the white color most probably a leftover from Soda theme since I based it on that.

Cheers!

**Comment by lijuenc** [comment]
thanks, I got the new version through package control today and it was fixed.
